# For most projects, this workflow file will not need changing; you simply need
# to commit it to your repository.
#
# You may wish to alter this file to override the set of languages analyzed,
# or to provide custom queries or build logic.
#
# ******** NOTE ********
# We have attempted to detect the languages in your repository. Please check
# the `language` matrix defined below to confirm you have the correct set of
# supported CodeQL languages.
#
name: "WorflowN7"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '00 4 * * *' # runs at 4:00 everyday

jobs:
  test_compilation:
    name: Test Compilation
    runs-on: 'ubuntu-latest'
    timeout-minutes: 360
    permissions:
      security-events: write
        
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Check commit messages
      run: |
        LAST_COMMIT_SHA=${{ github.sha }}
        
        COMMIT_MESSAGES=$(git log --format=%s $LAST_COMMIT_SHA)

        for COMMIT_MESSAGE in $COMMIT_MESSAGES; do
          echo "$COMMIT_MESSAGE"
        done

    - name: Set up JDK 7
      uses: actions/setup-java@v3
      with:
        java-version: '7'
        distribution: 'oracle'

    - name: Run build the code
      run: javac main.java
        
